require same openssl version, otherwise httplib fails
$ python -c "import httplib;print httplib.HTTPSConnection"
Traceback (most recent call last): File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'HTTPSConnection'

similar error here:
https://bugs.launchpad.net/bzr/+bug/411296